# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baDldvkixRrK_fjHWBjDpQGxVE7J1cKk
"""

import matplotlib.pyplot as plt

#dados extraídos do detran
anos = ['2019', '2020', '2021', '2022', '2023', '2024', '2025']
sinistros_ano = [121216, 113974, 126416, 130679, 140501, 135590, 102098]

#calculo das médias dos últimos 5 anos (21 á 25)
ultimos_5_anos = sinistros_ano[-5:]
media_5_anos = sum(ultimos_5_anos) / len(ultimos_5_anos)

#criando imagem
plt.figure(figsize=(10, 5))
plt.plot(anos, sinistros_ano, marker='o', linestyle='-', color='#0f45a8', linewidth=2.5)

#formatando o gráfico
plt.title('Evolução de Sinistros por Ano', fontsize=14, fontweight='bold')
plt.xlabel('Ano', fontsize=12)
plt.ylabel('Quantidade de Sinistros', fontsize=14)
plt.grid(True, linestyle='--', alpha=0.6)
plt.ylim(0, 160000)

#média em baixo dos gráficos
plt.subplots_adjust(bottom=0.2)
texto_media = f'Média dos últimos 5 anos (2021-2025): {media_5_anos:,.0f}'.replace(',', '.')
plt.figtext(0.5, 0.04, texto_media, ha='center', fontsize=11, fontfamily='sans-serif',
bbox=dict(facecolor='#f0f0f0', edgecolor='gray'))
plt.subplots_adjust(bottom=0.1)

plt.tight_layout()
plt.show()

print("\n" + "-"*50 + "\n")

#dados extraídos do noturno
dias_semana = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo']
sinistros_noite = [30532, 33210, 34582, 36349, 47202, 46738, 40315]

#fazendo média dos dados
media_sinistros_noturnos = sum(sinistros_noite)/len(sinistros_noite)

#imagens
plt.figure(figsize=(10, 5))
plt.plot(dias_semana, sinistros_noite, marker='o', linestyle='-', color='#0f45a8', linewidth=2.5)

#arrumando o gráfico
plt.title('Sinistros Noturnos por Dia da Semana', fontsize=14, fontweight='bold')
plt.xlabel('Dia da Semana', fontsize=12)
plt.ylabel('Quantidade de Sinistros (Noite)', fontsize=14, fontfamily='sans-serif')
plt.grid(True, linestyle='--', alpha=0.6)
plt.ylim(0, 60000)

#média em baixo dos gráficos
plt.subplots_adjust(bottom=0.2)
texto_media = f'Média dos Sinistros Noturnos por Dia da Semana: {media_sinistros_noturnos:,.0f}'.replace(',', '.')
plt.figtext(0.5, 0.04, texto_media, ha='center', fontsize=11, fontfamily='sans-serif',
bbox=dict(facecolor='#f0f0f0', edgecolor='gray'))
plt.subplots_adjust(bottom=0.1)

plt.tight_layout()
plt.show()